FieldDiemensions:
  GoalDepth: 8
  GoalWidth: 60
  InnerLength: 183
  InnerWidth: 122
  OuterLength: 243
  OuterWidth: 182
Gui:
  Commandline: false
  Debugger: false
  SamplingRate: 20
  Fast: true
Robot0:
  Active: false
  DefektTime: 24000
Robot1:
  Active: false
  DefektTime: 24000
Robot2:
  Active: true
  DefektTime: 100
Robot3:
  Active: false
  DefektTime: 24000
Rules:
  DoubleDefense: true
  LagOfProgress: 2000
  LagOfProgressActive: false
  OutOfBounce: true
  Pushing: true
  Timeout: 15000
  TimeoutActive: false
  TestMode: 1
